apiVersion: v1
kind: Secret
metadata:
  name: innodbclu1-passwords
type: Opaque
stringData:
  rootHost: '%'
  rootPassword: CFG_INNODB_ROOTPASSWORD
  rootUser: root
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: innodbclu1
spec:
  secretName: innodbclu1-passwords
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 2

